name: debug_vidface_count_param
model_type: VidFaceModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: TUFS145K
    type: TUFS145KDataset
    dataroot_gt: /data2/wei/vox-unalign/GT
    dataroot_lq: /data2/wei/vox-unalign/LR
    dataroot_flow: ~
    meta_info_file: basicsr/data/meta_info/tufs_train.txt
    io_backend:
      type: disk

    num_frame: 7
    gt_size: 96
    interval_list: [1]
    random_reverse: false
    use_flip: true
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: TUFS145K_VAL
    type: VideoTestTUFS145KDataset
    dataroot_gt: /data2/wei/vox-unalign/GT
    dataroot_lq: /data2/wei/vox-unalign/LR
    meta_info_file: basicsr/data/meta_info/tufs_val.txt 
    io_backend:
      type: disk

    cache_data: false
    num_frame: 7
    padding: reflection_circle


# network structures
network_g:
  type: VidFace
  
# path
path:
  pretrain_model_g: ~
  strict_load: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamWLA
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [600000, 600000, 600000, 1000000, 1280000]
    restart_weights: [1, 0.5, 0.5, 0.8, 0.8]
    eta_min: !!float 1e-6

  total_iter: 600000
  warmup_iter: -1  # no warm up
  tsa_iter: 1
  dcn_lr_mul: 1

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: sum
    
# validation settings
val:
  val_freq: !!float 2e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true

